name: Run Go tests

on:
  pull_request:
    branches: [dev, stage, master]

jobs:
  test:
    permissions:
      contents: read
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Configure Git for private modules
        run: git config --global url."https://${{ secrets.GH_READ_PAT }}@github.com/".insteadOf "https://github.com/"

      - name: Install dependencies
        run: go mod download

      - name: Run unit tests
        run: go test $(go list ./... | grep -v /e2e)

      - name: Run e2e tests
        run: |
          echo "⚠️ Running E2E tests - this may take several seconds ..."
          go test ./e2e
